// Generated by starc (STAR Schema Compiler). DO NOT EDIT MANUALLY.
#pragma once

#include "core_sysdb/app_types.h"
#include "core_sysdb/led_types.h"
#include "core_sysdb/WalTypes.h"
#include "core_sysdb/AudioRates.h"
#include <cstdint>
#include <string>
#include <cstring>

// ─────────────────────────────────────────────────────────────────────────────
// Component-level change bitmasks
// ─────────────────────────────────────────────────────────────────────────────
using ComponentMask = uint32_t;

namespace COMP {
    static constexpr ComponentMask SYSTEM       = 0x00010000u;
    static constexpr ComponentMask AUDIO        = 0x00020000u;
    static constexpr ComponentMask PIPELINE     = 0x00040000u;
    static constexpr ComponentMask ASSISTANT    = 0x00080000u;
    static constexpr ComponentMask LED          = 0x00100000u;
    static constexpr ComponentMask MQTT         = 0x00200000u;
    static constexpr ComponentMask ALARM        = 0x00400000u;
    static constexpr ComponentMask BLUETOOTH    = 0x00800000u;
    static constexpr ComponentMask MEDIA        = 0x01000000u;
    static constexpr ComponentMask BT_COMPANION = BLUETOOTH;
    static constexpr ComponentMask ALL          = 0xFFFF0000u;
}

// ─────────────────────────────────────────────────────────────────────────────
// Enums defined in STAR schema
// ─────────────────────────────────────────────────────────────────────────────
enum class MediaPlaybackState : uint8_t {
    IDLE = 0,
    RESOLVING = 1,
    BUFFERING = 2,
    PLAYING = 3,
    PAUSED = 4,
    ERROR_STATE = 5
};

// ─────────────────────────────────────────────────────────────────────────────
// Per-field notification bits
// ─────────────────────────────────────────────────────────────────────────────
namespace BIT_SYSTEM {
    static constexpr ComponentMask WIFI_CONNECTED   = (1u << 0);
    static constexpr ComponentMask NETWORK_STATE    = (1u << 2);
    static constexpr ComponentMask SERVER_IP        = (1u << 1);
}

namespace BIT_AUDIO {
    static constexpr ComponentMask SAMPLE_RATE      = (1u << 0);
    static constexpr ComponentMask HW_RATE          = (1u << 7);
    static constexpr ComponentMask MIC_GAIN         = (1u << 1);
    static constexpr ComponentMask SPEAKER_VOLUME   = (1u << 2);
    static constexpr ComponentMask MIC_ENABLED      = (1u << 3);
    static constexpr ComponentMask ASST_SPEAKING    = (1u << 4);
    static constexpr ComponentMask SESSION_ACTIVE   = (1u << 5);
    static constexpr ComponentMask TURN_COMPLETE    = (1u << 6);
    static constexpr ComponentMask LAST_ACTIVITY    = (1u << 8);
    static constexpr ComponentMask WAV_PLAYING      = (1u << 9);
    static constexpr ComponentMask RECORD_CHANNELS  = (1u << 10);
}

namespace BIT_PIPELINE {
    static constexpr ComponentMask MODE             = (1u << 0);
    static constexpr ComponentMask RTP_TX           = (1u << 1);
    static constexpr ComponentMask RTP_RX           = (1u << 2);
}

namespace BIT_ASSISTANT {
    static constexpr ComponentMask SESSION_STATE    = (1u << 0);
    static constexpr ComponentMask VISUAL_STATE     = (1u << 1);
    static constexpr ComponentMask CONNECT_REQ      = (1u << 3);
    static constexpr ComponentMask WS_STATE         = (1u << 2);
}

namespace BIT_LED {
    static constexpr ComponentMask MODE             = (1u << 0);
    static constexpr ComponentMask COLOR            = (1u << 1);
    static constexpr ComponentMask SPEED            = (1u << 2);
}

namespace BIT_MQTT {
    static constexpr ComponentMask CONNECTED        = (1u << 0);
}

namespace BIT_ALARM {
    static constexpr ComponentMask PLAYING          = (1u << 0);
    static constexpr ComponentMask STOP_REQUESTED   = (1u << 1);
}

namespace BIT_BLUETOOTH {
    static constexpr ComponentMask CONNECTED        = (1u << 0);
    static constexpr ComponentMask DEVICE_NAME      = (1u << 1);
    static constexpr ComponentMask MAC_ADDRESS      = (1u << 2);
    static constexpr ComponentMask STATUS           = (1u << 3);
    static constexpr ComponentMask READY            = CONNECTED;
}
namespace BIT_BT_COMPANION = BIT_BLUETOOTH;

namespace BIT_MEDIA {
    static constexpr ComponentMask STATE            = (1u << 0);
    static constexpr ComponentMask TRACK            = (1u << 1);
    static constexpr ComponentMask POSITION         = (1u << 6);
    static constexpr ComponentMask DURATION         = (1u << 7);
    static constexpr ComponentMask REPEAT           = (1u << 2);
    static constexpr ComponentMask DUCKED           = (1u << 3);
    static constexpr ComponentMask AUTOPLAY         = (1u << 4);
    static constexpr ComponentMask CACHE            = (1u << 5);
    static constexpr ComponentMask TARGET           = (1u << 8);
    static constexpr ComponentMask CMD              = (1u << 9);
}

// ─────────────────────────────────────────────────────────────────────────────
// SystemState Field Definitions with FieldAccess Annotations
// ─────────────────────────────────────────────────────────────────────────────
#define SYSTEM_FIELDS \
    X(bool, wifi_connected, false, BIT_SYSTEM::WIFI_CONNECTED, FieldAccess::ReadOnly) \
    X(NetworkState, network_state, NetworkState::Disconnected, BIT_SYSTEM::NETWORK_STATE, FieldAccess::ReadOnly) \
    X_STR(server_ip, 32, "192.168.1.18", BIT_SYSTEM::SERVER_IP, FieldAccess::Writable) \
    X(int, wifi_max_retries, 5, 0, FieldAccess::Writable)

#define AUDIO_FIELDS \
    X(uint32_t, sample_rate, LOCAL_SAMPLE_RATE, BIT_AUDIO::SAMPLE_RATE, FieldAccess::ReadOnly) \
    X(uint32_t, current_hardware_rate, LOCAL_SAMPLE_RATE, BIT_AUDIO::HW_RATE, FieldAccess::ReadOnly) \
    X(float, mic_gain_db, 60.0f, BIT_AUDIO::MIC_GAIN, FieldAccess::Writable) \
    X(int, speaker_volume, 80, BIT_AUDIO::SPEAKER_VOLUME, FieldAccess::Writable) \
    X(bool, mic_enabled, true, BIT_AUDIO::MIC_ENABLED, FieldAccess::Writable) \
    X(bool, assistant_speaking, false, BIT_AUDIO::ASST_SPEAKING, FieldAccess::ReadOnly) \
    X(bool, session_active, false, BIT_AUDIO::SESSION_ACTIVE, FieldAccess::ReadOnly) \
    X(bool, turn_complete_pending, false, BIT_AUDIO::TURN_COMPLETE, FieldAccess::ReadOnly) \
    X(uint64_t, last_activity_ms, 0, BIT_AUDIO::LAST_ACTIVITY, FieldAccess::ReadOnly) \
    X(uint32_t, buffer_size, 131072, 0, FieldAccess::ReadOnly) \
    X(uint16_t, rtp_tx_port, 5005, 0, FieldAccess::Writable) \
    X(uint16_t, rtp_rx_port, 5005, 0, FieldAccess::Writable) \
    X(AudioStreamFormat, stream_format, AudioStreamFormat::PCM_S16LE, 0, FieldAccess::Writable) \
    X(bool, wav_playing, false, BIT_AUDIO::WAV_PLAYING, FieldAccess::ReadOnly) \
    X(uint32_t, wav_sample_rate, 16000, 0, FieldAccess::ReadOnly) \
    X(bool, wav_prefetched, false, 0, FieldAccess::ReadOnly) \
    X(bool, record_all_mic_channels, true, BIT_AUDIO::RECORD_CHANNELS, FieldAccess::Writable)

#define PIPELINE_FIELDS \
    X(PipelineMode, mode, PipelineMode::WAKE_IDLE, BIT_PIPELINE::MODE, FieldAccess::Writable) \
    X(bool, rtp_tx_en, false, BIT_PIPELINE::RTP_TX, FieldAccess::Writable) \
    X(bool, rtp_rx_en, false, BIT_PIPELINE::RTP_RX, FieldAccess::Writable) \
    X(bool, rtp_enabled, false, 0, FieldAccess::Writable)

#define ASSISTANT_FIELDS \
    X(AssistantState, session_state, AssistantState::Idle, BIT_ASSISTANT::SESSION_STATE, FieldAccess::ReadOnly) \
    X(AssistantVisualState, visual_state, AssistantVisualState::Offline, BIT_ASSISTANT::VISUAL_STATE, FieldAccess::ReadOnly) \
    X(bool, connect_requested, false, BIT_ASSISTANT::CONNECT_REQ, FieldAccess::Writable) \
    X(WsState, ws_state, WsState::DISCONNECTED, BIT_ASSISTANT::WS_STATE, FieldAccess::ReadOnly) \
    X(bool, media_pending_idle, false, 0, FieldAccess::ReadOnly)

#define LED_FIELDS \
    X(LedMode, mode, LedMode::OFF, BIT_LED::MODE, FieldAccess::Writable) \
    X_COLOR(color, OFF_LED, BIT_LED::COLOR, FieldAccess::Writable) \
    X(uint32_t, speed_ms, 500, BIT_LED::SPEED, FieldAccess::Writable) \
    X(uint8_t, repeat, 0, 0, FieldAccess::Writable)

#define MQTT_FIELDS \
    X(bool, connected, false, BIT_MQTT::CONNECTED, FieldAccess::ReadOnly)

#define ALARM_FIELDS \
    X(bool, playing, false, BIT_ALARM::PLAYING, FieldAccess::ReadOnly) \
    X(bool, stop_requested, false, BIT_ALARM::STOP_REQUESTED, FieldAccess::Writable) \
    X(int, active_alarm_id, 0, 0, FieldAccess::Writable)

#define BLUETOOTH_FIELDS \
    X(bool, connected, false, BIT_BLUETOOTH::CONNECTED, FieldAccess::PiOrigin) \
    X_STR(device_name, 32, "", BIT_BLUETOOTH::DEVICE_NAME, FieldAccess::PiOrigin) \
    X_STR(mac_address, 18, "", BIT_BLUETOOTH::MAC_ADDRESS, FieldAccess::PiOrigin) \
    X(int8_t, rssi, 0, BIT_BLUETOOTH::STATUS, FieldAccess::PiOrigin)

#define MEDIA_FIELDS \
    X(MediaPlaybackState, state, MediaPlaybackState::IDLE, BIT_MEDIA::STATE, FieldAccess::Writable) \
    X_STR(active_song_id, 64, "", BIT_MEDIA::TRACK, FieldAccess::Writable) \
    X_STR(title, 64, "", BIT_MEDIA::TRACK, FieldAccess::Writable) \
    X_STR(artist, 64, "", BIT_MEDIA::TRACK, FieldAccess::Writable) \
    X(uint32_t, position_ms, 0, BIT_MEDIA::POSITION, FieldAccess::Writable) \
    X(uint32_t, duration_ms, 0, BIT_MEDIA::DURATION, FieldAccess::Writable) \
    X(bool, seekable, false, 0, FieldAccess::ReadOnly) \
    X(uint8_t, repeat_mode, 0, BIT_MEDIA::REPEAT, FieldAccess::Writable) \
    X(bool, is_ducked, false, BIT_MEDIA::DUCKED, FieldAccess::ReadOnly) \
    X(bool, autoplay_enabled, true, BIT_MEDIA::AUTOPLAY, FieldAccess::Writable) \
    X(bool, cache_downloads, false, BIT_MEDIA::CACHE, FieldAccess::Writable) \
    X(MediaOutputTarget, output_target, MediaOutputTarget::LOCAL, BIT_MEDIA::TARGET, FieldAccess::ReadOnly) \
    X(MediaPendingCommand, pending_command, {}, BIT_MEDIA::CMD, FieldAccess::Writable)

// ─────────────────────────────────────────────────────────────────────────────
// SystemState — the single shared in-memory database
// ─────────────────────────────────────────────────────────────────────────────
struct SystemState {
    #define X(type, name, def, bit, access) type name = def;
    #define X_STR(name, size, def, bit, access) char name[size] = def;
    #define X_COLOR(name, def, bit, access) RgbColor name = def;

    // ── COMP::SYSTEM ───────────────────────────────────────────
    struct {
        SYSTEM_FIELDS
    } system;

    // ── COMP::AUDIO ───────────────────────────────────────────
    struct {
        AUDIO_FIELDS
    } audio;

    // ── COMP::PIPELINE ───────────────────────────────────────────
    struct {
        PIPELINE_FIELDS
    } pipeline;

    // ── COMP::ASSISTANT ───────────────────────────────────────────
    struct {
        ASSISTANT_FIELDS
    } assistant;

    // ── COMP::LED ───────────────────────────────────────────
    struct {
        LED_FIELDS
    } led;

    // ── COMP::MQTT ───────────────────────────────────────────
    struct {
        MQTT_FIELDS
    } mqtt;

    // ── COMP::ALARM ───────────────────────────────────────────
    struct {
        ALARM_FIELDS
    } alarm;

    // ── COMP::BLUETOOTH ───────────────────────────────────────────
    struct {
        BLUETOOTH_FIELDS
    } bluetooth;

    // ── COMP::MEDIA ───────────────────────────────────────────
    struct {
        MEDIA_FIELDS
    } media;

    #undef X
    #undef X_STR
    #undef X_COLOR
};

// ─────────────────────────────────────────────────────────────────────────────
// STAR Wire Tag Namespaces (Sequential uint8_t field indices per component)
// ─────────────────────────────────────────────────────────────────────────────
namespace TAG_SYSTEM {
    enum : uint8_t {
        #define X(type, name, def, bit, access) name,
        #define X_STR(name, size, def, bit, access) name,
        #define X_COLOR(name, def, bit, access) name,
        SYSTEM_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
        _COUNT
    };
}

namespace TAG_AUDIO {
    enum : uint8_t {
        #define X(type, name, def, bit, access) name,
        #define X_STR(name, size, def, bit, access) name,
        #define X_COLOR(name, def, bit, access) name,
        AUDIO_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
        _COUNT
    };
}

namespace TAG_PIPELINE {
    enum : uint8_t {
        #define X(type, name, def, bit, access) name,
        #define X_STR(name, size, def, bit, access) name,
        #define X_COLOR(name, def, bit, access) name,
        PIPELINE_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
        _COUNT
    };
}

namespace TAG_ASSISTANT {
    enum : uint8_t {
        #define X(type, name, def, bit, access) name,
        #define X_STR(name, size, def, bit, access) name,
        #define X_COLOR(name, def, bit, access) name,
        ASSISTANT_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
        _COUNT
    };
}

namespace TAG_LED {
    enum : uint8_t {
        #define X(type, name, def, bit, access) name,
        #define X_STR(name, size, def, bit, access) name,
        #define X_COLOR(name, def, bit, access) name,
        LED_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
        _COUNT
    };
}

namespace TAG_MQTT {
    enum : uint8_t {
        #define X(type, name, def, bit, access) name,
        #define X_STR(name, size, def, bit, access) name,
        #define X_COLOR(name, def, bit, access) name,
        MQTT_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
        _COUNT
    };
}

namespace TAG_ALARM {
    enum : uint8_t {
        #define X(type, name, def, bit, access) name,
        #define X_STR(name, size, def, bit, access) name,
        #define X_COLOR(name, def, bit, access) name,
        ALARM_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
        _COUNT
    };
}

namespace TAG_BLUETOOTH {
    enum : uint8_t {
        #define X(type, name, def, bit, access) name,
        #define X_STR(name, size, def, bit, access) name,
        #define X_COLOR(name, def, bit, access) name,
        BLUETOOTH_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
        _COUNT
    };
}

namespace TAG_MEDIA {
    enum : uint8_t {
        #define X(type, name, def, bit, access) name,
        #define X_STR(name, size, def, bit, access) name,
        #define X_COLOR(name, def, bit, access) name,
        MEDIA_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
        _COUNT
    };
}

// ─────────────────────────────────────────────────────────────────────────────
// Component and Field Helpers
// ─────────────────────────────────────────────────────────────────────────────
inline constexpr ComponentMask getComponentMask(ComponentId comp) {
    return (1u << (16 + static_cast<uint8_t>(comp)));
}

inline constexpr ComponentId getComponentId(ComponentMask comp) {
    switch (comp & 0xFFFF0000u) {
        case COMP::SYSTEM: return ComponentId::SYSTEM;
        case COMP::AUDIO: return ComponentId::AUDIO;
        case COMP::PIPELINE: return ComponentId::PIPELINE;
        case COMP::ASSISTANT: return ComponentId::ASSISTANT;
        case COMP::LED: return ComponentId::LED;
        case COMP::MQTT: return ComponentId::MQTT;
        case COMP::ALARM: return ComponentId::ALARM;
        case COMP::BLUETOOTH: return ComponentId::BLUETOOTH;
        case COMP::MEDIA: return ComponentId::MEDIA;
        default: return ComponentId::COUNT;
    }
}

inline FieldAccess getFieldAccess(ComponentId comp, uint8_t field_tag) {
    switch (comp) {
        case ComponentId::SYSTEM: {
            static constexpr FieldAccess s_access[] = {
                #define X(type, name, def, bit, access) access,
                #define X_STR(name, size, def, bit, access) access,
                #define X_COLOR(name, def, bit, access) access,
                SYSTEM_FIELDS
                #undef X
                #undef X_STR
                #undef X_COLOR
            };
            if (field_tag < sizeof(s_access)/sizeof(s_access[0])) return s_access[field_tag];
            break;
        }
        case ComponentId::AUDIO: {
            static constexpr FieldAccess s_access[] = {
                #define X(type, name, def, bit, access) access,
                #define X_STR(name, size, def, bit, access) access,
                #define X_COLOR(name, def, bit, access) access,
                AUDIO_FIELDS
                #undef X
                #undef X_STR
                #undef X_COLOR
            };
            if (field_tag < sizeof(s_access)/sizeof(s_access[0])) return s_access[field_tag];
            break;
        }
        case ComponentId::PIPELINE: {
            static constexpr FieldAccess s_access[] = {
                #define X(type, name, def, bit, access) access,
                #define X_STR(name, size, def, bit, access) access,
                #define X_COLOR(name, def, bit, access) access,
                PIPELINE_FIELDS
                #undef X
                #undef X_STR
                #undef X_COLOR
            };
            if (field_tag < sizeof(s_access)/sizeof(s_access[0])) return s_access[field_tag];
            break;
        }
        case ComponentId::ASSISTANT: {
            static constexpr FieldAccess s_access[] = {
                #define X(type, name, def, bit, access) access,
                #define X_STR(name, size, def, bit, access) access,
                #define X_COLOR(name, def, bit, access) access,
                ASSISTANT_FIELDS
                #undef X
                #undef X_STR
                #undef X_COLOR
            };
            if (field_tag < sizeof(s_access)/sizeof(s_access[0])) return s_access[field_tag];
            break;
        }
        case ComponentId::LED: {
            static constexpr FieldAccess s_access[] = {
                #define X(type, name, def, bit, access) access,
                #define X_STR(name, size, def, bit, access) access,
                #define X_COLOR(name, def, bit, access) access,
                LED_FIELDS
                #undef X
                #undef X_STR
                #undef X_COLOR
            };
            if (field_tag < sizeof(s_access)/sizeof(s_access[0])) return s_access[field_tag];
            break;
        }
        case ComponentId::MQTT: {
            static constexpr FieldAccess s_access[] = {
                #define X(type, name, def, bit, access) access,
                #define X_STR(name, size, def, bit, access) access,
                #define X_COLOR(name, def, bit, access) access,
                MQTT_FIELDS
                #undef X
                #undef X_STR
                #undef X_COLOR
            };
            if (field_tag < sizeof(s_access)/sizeof(s_access[0])) return s_access[field_tag];
            break;
        }
        case ComponentId::ALARM: {
            static constexpr FieldAccess s_access[] = {
                #define X(type, name, def, bit, access) access,
                #define X_STR(name, size, def, bit, access) access,
                #define X_COLOR(name, def, bit, access) access,
                ALARM_FIELDS
                #undef X
                #undef X_STR
                #undef X_COLOR
            };
            if (field_tag < sizeof(s_access)/sizeof(s_access[0])) return s_access[field_tag];
            break;
        }
        case ComponentId::BLUETOOTH: {
            static constexpr FieldAccess s_access[] = {
                #define X(type, name, def, bit, access) access,
                #define X_STR(name, size, def, bit, access) access,
                #define X_COLOR(name, def, bit, access) access,
                BLUETOOTH_FIELDS
                #undef X
                #undef X_STR
                #undef X_COLOR
            };
            if (field_tag < sizeof(s_access)/sizeof(s_access[0])) return s_access[field_tag];
            break;
        }
        case ComponentId::MEDIA: {
            static constexpr FieldAccess s_access[] = {
                #define X(type, name, def, bit, access) access,
                #define X_STR(name, size, def, bit, access) access,
                #define X_COLOR(name, def, bit, access) access,
                MEDIA_FIELDS
                #undef X
                #undef X_STR
                #undef X_COLOR
            };
            if (field_tag < sizeof(s_access)/sizeof(s_access[0])) return s_access[field_tag];
            break;
        }
        default: break;
    }
    return FieldAccess::ReadOnly;
}

inline uint8_t getFieldCount(ComponentId comp) {
    switch (comp) {
        case ComponentId::SYSTEM: return TAG_SYSTEM::_COUNT;
        case ComponentId::AUDIO: return TAG_AUDIO::_COUNT;
        case ComponentId::PIPELINE: return TAG_PIPELINE::_COUNT;
        case ComponentId::ASSISTANT: return TAG_ASSISTANT::_COUNT;
        case ComponentId::LED: return TAG_LED::_COUNT;
        case ComponentId::MQTT: return TAG_MQTT::_COUNT;
        case ComponentId::ALARM: return TAG_ALARM::_COUNT;
        case ComponentId::BLUETOOTH: return TAG_BLUETOOTH::_COUNT;
        case ComponentId::MEDIA: return TAG_MEDIA::_COUNT;
        default: return 0;
    }
}

inline const char* getFieldName(ComponentId comp, uint8_t field_tag) {
    switch (comp) {
        case ComponentId::SYSTEM: {
            static const char* const s_names[] = {
                #define X(type, name, def, bit, access) #name,
                #define X_STR(name, size, def, bit, access) #name,
                #define X_COLOR(name, def, bit, access) #name,
                SYSTEM_FIELDS
                #undef X
                #undef X_STR
                #undef X_COLOR
            };
            if (field_tag < sizeof(s_names)/sizeof(s_names[0])) return s_names[field_tag];
            break;
        }
        case ComponentId::AUDIO: {
            static const char* const s_names[] = {
                #define X(type, name, def, bit, access) #name,
                #define X_STR(name, size, def, bit, access) #name,
                #define X_COLOR(name, def, bit, access) #name,
                AUDIO_FIELDS
                #undef X
                #undef X_STR
                #undef X_COLOR
            };
            if (field_tag < sizeof(s_names)/sizeof(s_names[0])) return s_names[field_tag];
            break;
        }
        case ComponentId::PIPELINE: {
            static const char* const s_names[] = {
                #define X(type, name, def, bit, access) #name,
                #define X_STR(name, size, def, bit, access) #name,
                #define X_COLOR(name, def, bit, access) #name,
                PIPELINE_FIELDS
                #undef X
                #undef X_STR
                #undef X_COLOR
            };
            if (field_tag < sizeof(s_names)/sizeof(s_names[0])) return s_names[field_tag];
            break;
        }
        case ComponentId::ASSISTANT: {
            static const char* const s_names[] = {
                #define X(type, name, def, bit, access) #name,
                #define X_STR(name, size, def, bit, access) #name,
                #define X_COLOR(name, def, bit, access) #name,
                ASSISTANT_FIELDS
                #undef X
                #undef X_STR
                #undef X_COLOR
            };
            if (field_tag < sizeof(s_names)/sizeof(s_names[0])) return s_names[field_tag];
            break;
        }
        case ComponentId::LED: {
            static const char* const s_names[] = {
                #define X(type, name, def, bit, access) #name,
                #define X_STR(name, size, def, bit, access) #name,
                #define X_COLOR(name, def, bit, access) #name,
                LED_FIELDS
                #undef X
                #undef X_STR
                #undef X_COLOR
            };
            if (field_tag < sizeof(s_names)/sizeof(s_names[0])) return s_names[field_tag];
            break;
        }
        case ComponentId::MQTT: {
            static const char* const s_names[] = {
                #define X(type, name, def, bit, access) #name,
                #define X_STR(name, size, def, bit, access) #name,
                #define X_COLOR(name, def, bit, access) #name,
                MQTT_FIELDS
                #undef X
                #undef X_STR
                #undef X_COLOR
            };
            if (field_tag < sizeof(s_names)/sizeof(s_names[0])) return s_names[field_tag];
            break;
        }
        case ComponentId::ALARM: {
            static const char* const s_names[] = {
                #define X(type, name, def, bit, access) #name,
                #define X_STR(name, size, def, bit, access) #name,
                #define X_COLOR(name, def, bit, access) #name,
                ALARM_FIELDS
                #undef X
                #undef X_STR
                #undef X_COLOR
            };
            if (field_tag < sizeof(s_names)/sizeof(s_names[0])) return s_names[field_tag];
            break;
        }
        case ComponentId::BLUETOOTH: {
            static const char* const s_names[] = {
                #define X(type, name, def, bit, access) #name,
                #define X_STR(name, size, def, bit, access) #name,
                #define X_COLOR(name, def, bit, access) #name,
                BLUETOOTH_FIELDS
                #undef X
                #undef X_STR
                #undef X_COLOR
            };
            if (field_tag < sizeof(s_names)/sizeof(s_names[0])) return s_names[field_tag];
            break;
        }
        case ComponentId::MEDIA: {
            static const char* const s_names[] = {
                #define X(type, name, def, bit, access) #name,
                #define X_STR(name, size, def, bit, access) #name,
                #define X_COLOR(name, def, bit, access) #name,
                MEDIA_FIELDS
                #undef X
                #undef X_STR
                #undef X_COLOR
            };
            if (field_tag < sizeof(s_names)/sizeof(s_names[0])) return s_names[field_tag];
            break;
        }
        default: break;
    }
    return "unknown";
}

inline bool isFieldWritable(ComponentId comp, uint8_t field_tag) {
    FieldAccess acc = getFieldAccess(comp, field_tag);
    return acc != FieldAccess::ReadOnly;
}
