// Generated by starc (STAR Schema Compiler). DO NOT EDIT MANUALLY.
#include "core_sysdb/SysDbCodec.h"
#include <cstring>

namespace SysDbCodec {

ComponentMask diffState(const SystemState& old_s, const SystemState& new_s) {
    ComponentMask changed = 0;

    // ── SYSTEM_FIELDS ──────────────────────────────────────────
    {
        #define MARK(bit) changed |= ((bit) != 0 ? (COMP::SYSTEM | (bit)) : COMP::SYSTEM)
        #define X(type, name, def, bit, access) if (old_s.system.name != new_s.system.name) MARK(bit);
        #define X_STR(name, size, def, bit, access) if (std::strncmp(old_s.system.name, new_s.system.name, size) != 0) MARK(bit);
        #define X_COLOR(name, def, bit, access) if (old_s.system.name.r != new_s.system.name.r || old_s.system.name.g != new_s.system.name.g || old_s.system.name.b != new_s.system.name.b) MARK(bit);
        SYSTEM_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
        #undef MARK
    }

    // ── AUDIO_FIELDS ──────────────────────────────────────────
    {
        #define MARK(bit) changed |= ((bit) != 0 ? (COMP::AUDIO | (bit)) : COMP::AUDIO)
        #define X(type, name, def, bit, access) if (old_s.audio.name != new_s.audio.name) MARK(bit);
        #define X_STR(name, size, def, bit, access) if (std::strncmp(old_s.audio.name, new_s.audio.name, size) != 0) MARK(bit);
        #define X_COLOR(name, def, bit, access) if (old_s.audio.name.r != new_s.audio.name.r || old_s.audio.name.g != new_s.audio.name.g || old_s.audio.name.b != new_s.audio.name.b) MARK(bit);
        AUDIO_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
        #undef MARK
    }

    // ── PIPELINE_FIELDS ──────────────────────────────────────────
    {
        #define MARK(bit) changed |= ((bit) != 0 ? (COMP::PIPELINE | (bit)) : COMP::PIPELINE)
        #define X(type, name, def, bit, access) if (old_s.pipeline.name != new_s.pipeline.name) MARK(bit);
        #define X_STR(name, size, def, bit, access) if (std::strncmp(old_s.pipeline.name, new_s.pipeline.name, size) != 0) MARK(bit);
        #define X_COLOR(name, def, bit, access) if (old_s.pipeline.name.r != new_s.pipeline.name.r || old_s.pipeline.name.g != new_s.pipeline.name.g || old_s.pipeline.name.b != new_s.pipeline.name.b) MARK(bit);
        PIPELINE_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
        #undef MARK
    }

    // ── ASSISTANT_FIELDS ──────────────────────────────────────────
    {
        #define MARK(bit) changed |= ((bit) != 0 ? (COMP::ASSISTANT | (bit)) : COMP::ASSISTANT)
        #define X(type, name, def, bit, access) if (old_s.assistant.name != new_s.assistant.name) MARK(bit);
        #define X_STR(name, size, def, bit, access) if (std::strncmp(old_s.assistant.name, new_s.assistant.name, size) != 0) MARK(bit);
        #define X_COLOR(name, def, bit, access) if (old_s.assistant.name.r != new_s.assistant.name.r || old_s.assistant.name.g != new_s.assistant.name.g || old_s.assistant.name.b != new_s.assistant.name.b) MARK(bit);
        ASSISTANT_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
        #undef MARK
    }

    // ── LED_FIELDS ──────────────────────────────────────────
    {
        #define MARK(bit) changed |= ((bit) != 0 ? (COMP::LED | (bit)) : COMP::LED)
        #define X(type, name, def, bit, access) if (old_s.led.name != new_s.led.name) MARK(bit);
        #define X_STR(name, size, def, bit, access) if (std::strncmp(old_s.led.name, new_s.led.name, size) != 0) MARK(bit);
        #define X_COLOR(name, def, bit, access) if (old_s.led.name.r != new_s.led.name.r || old_s.led.name.g != new_s.led.name.g || old_s.led.name.b != new_s.led.name.b) MARK(bit);
        LED_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
        #undef MARK
    }

    // ── ALARM_FIELDS ──────────────────────────────────────────
    {
        #define MARK(bit) changed |= ((bit) != 0 ? (COMP::ALARM | (bit)) : COMP::ALARM)
        #define X(type, name, def, bit, access) if (old_s.alarm.name != new_s.alarm.name) MARK(bit);
        #define X_STR(name, size, def, bit, access) if (std::strncmp(old_s.alarm.name, new_s.alarm.name, size) != 0) MARK(bit);
        #define X_COLOR(name, def, bit, access) if (old_s.alarm.name.r != new_s.alarm.name.r || old_s.alarm.name.g != new_s.alarm.name.g || old_s.alarm.name.b != new_s.alarm.name.b) MARK(bit);
        ALARM_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
        #undef MARK
    }

    // ── BLUETOOTH_FIELDS ──────────────────────────────────────────
    {
        #define MARK(bit) changed |= ((bit) != 0 ? (COMP::BLUETOOTH | (bit)) : COMP::BLUETOOTH)
        #define X(type, name, def, bit, access) if (old_s.bluetooth.name != new_s.bluetooth.name) MARK(bit);
        #define X_STR(name, size, def, bit, access) if (std::strncmp(old_s.bluetooth.name, new_s.bluetooth.name, size) != 0) MARK(bit);
        #define X_COLOR(name, def, bit, access) if (old_s.bluetooth.name.r != new_s.bluetooth.name.r || old_s.bluetooth.name.g != new_s.bluetooth.name.g || old_s.bluetooth.name.b != new_s.bluetooth.name.b) MARK(bit);
        BLUETOOTH_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
        #undef MARK
    }

    // ── MEDIA_FIELDS ──────────────────────────────────────────
    {
        #define MARK(bit) changed |= ((bit) != 0 ? (COMP::MEDIA | (bit)) : COMP::MEDIA)
        #define X(type, name, def, bit, access) if (old_s.media.name != new_s.media.name) MARK(bit);
        #define X_STR(name, size, def, bit, access) if (std::strncmp(old_s.media.name, new_s.media.name, size) != 0) MARK(bit);
        #define X_COLOR(name, def, bit, access) if (old_s.media.name.r != new_s.media.name.r || old_s.media.name.g != new_s.media.name.g || old_s.media.name.b != new_s.media.name.b) MARK(bit);
        MEDIA_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
        #undef MARK
    }

    return changed;
}

} // namespace SysDbCodec
