// Generated by starc (STAR Schema Compiler). DO NOT EDIT MANUALLY.
#include "core_sysdb/SysDbCodec.h"
#include <cstring>

namespace SysDbCodec {

bool applyFieldWrite(SystemState& state, ComponentId comp, uint8_t field_tag, const uint8_t* val, uint8_t len) {
    switch (comp) {
        case ComponentId::SYSTEM: {
            uint8_t tag = 0;
            #define X(type, name, def, bit, access) \
                if (tag++ == field_tag) return deserializeAny(state.system.name, val, len);
            #define X_STR(name, size, def, bit, access) \
                if (tag++ == field_tag) return deserializeString(state.system.name, size, val, len);
            #define X_COLOR(name, def, bit, access) \
                if (tag++ == field_tag) return deserializeRgbColor(state.system.name, val, len);
            SYSTEM_FIELDS
            #undef X
            #undef X_STR
            #undef X_COLOR
            break;
        }
        case ComponentId::AUDIO: {
            uint8_t tag = 0;
            #define X(type, name, def, bit, access) \
                if (tag++ == field_tag) return deserializeAny(state.audio.name, val, len);
            #define X_STR(name, size, def, bit, access) \
                if (tag++ == field_tag) return deserializeString(state.audio.name, size, val, len);
            #define X_COLOR(name, def, bit, access) \
                if (tag++ == field_tag) return deserializeRgbColor(state.audio.name, val, len);
            AUDIO_FIELDS
            #undef X
            #undef X_STR
            #undef X_COLOR
            break;
        }
        case ComponentId::PIPELINE: {
            uint8_t tag = 0;
            #define X(type, name, def, bit, access) \
                if (tag++ == field_tag) return deserializeAny(state.pipeline.name, val, len);
            #define X_STR(name, size, def, bit, access) \
                if (tag++ == field_tag) return deserializeString(state.pipeline.name, size, val, len);
            #define X_COLOR(name, def, bit, access) \
                if (tag++ == field_tag) return deserializeRgbColor(state.pipeline.name, val, len);
            PIPELINE_FIELDS
            #undef X
            #undef X_STR
            #undef X_COLOR
            break;
        }
        case ComponentId::ASSISTANT: {
            uint8_t tag = 0;
            #define X(type, name, def, bit, access) \
                if (tag++ == field_tag) return deserializeAny(state.assistant.name, val, len);
            #define X_STR(name, size, def, bit, access) \
                if (tag++ == field_tag) return deserializeString(state.assistant.name, size, val, len);
            #define X_COLOR(name, def, bit, access) \
                if (tag++ == field_tag) return deserializeRgbColor(state.assistant.name, val, len);
            ASSISTANT_FIELDS
            #undef X
            #undef X_STR
            #undef X_COLOR
            break;
        }
        case ComponentId::LED: {
            uint8_t tag = 0;
            #define X(type, name, def, bit, access) \
                if (tag++ == field_tag) return deserializeAny(state.led.name, val, len);
            #define X_STR(name, size, def, bit, access) \
                if (tag++ == field_tag) return deserializeString(state.led.name, size, val, len);
            #define X_COLOR(name, def, bit, access) \
                if (tag++ == field_tag) return deserializeRgbColor(state.led.name, val, len);
            LED_FIELDS
            #undef X
            #undef X_STR
            #undef X_COLOR
            break;
        }
        case ComponentId::MQTT: {
            uint8_t tag = 0;
            #define X(type, name, def, bit, access) \
                if (tag++ == field_tag) return deserializeAny(state.mqtt.name, val, len);
            #define X_STR(name, size, def, bit, access) \
                if (tag++ == field_tag) return deserializeString(state.mqtt.name, size, val, len);
            #define X_COLOR(name, def, bit, access) \
                if (tag++ == field_tag) return deserializeRgbColor(state.mqtt.name, val, len);
            MQTT_FIELDS
            #undef X
            #undef X_STR
            #undef X_COLOR
            break;
        }
        case ComponentId::ALARM: {
            uint8_t tag = 0;
            #define X(type, name, def, bit, access) \
                if (tag++ == field_tag) return deserializeAny(state.alarm.name, val, len);
            #define X_STR(name, size, def, bit, access) \
                if (tag++ == field_tag) return deserializeString(state.alarm.name, size, val, len);
            #define X_COLOR(name, def, bit, access) \
                if (tag++ == field_tag) return deserializeRgbColor(state.alarm.name, val, len);
            ALARM_FIELDS
            #undef X
            #undef X_STR
            #undef X_COLOR
            break;
        }
        case ComponentId::BLUETOOTH: {
            uint8_t tag = 0;
            #define X(type, name, def, bit, access) \
                if (tag++ == field_tag) return deserializeAny(state.bluetooth.name, val, len);
            #define X_STR(name, size, def, bit, access) \
                if (tag++ == field_tag) return deserializeString(state.bluetooth.name, size, val, len);
            #define X_COLOR(name, def, bit, access) \
                if (tag++ == field_tag) return deserializeRgbColor(state.bluetooth.name, val, len);
            BLUETOOTH_FIELDS
            #undef X
            #undef X_STR
            #undef X_COLOR
            break;
        }
        case ComponentId::MEDIA: {
            uint8_t tag = 0;
            #define X(type, name, def, bit, access) \
                if (tag++ == field_tag) return deserializeAny(state.media.name, val, len);
            #define X_STR(name, size, def, bit, access) \
                if (tag++ == field_tag) return deserializeString(state.media.name, size, val, len);
            #define X_COLOR(name, def, bit, access) \
                if (tag++ == field_tag) return deserializeRgbColor(state.media.name, val, len);
            MEDIA_FIELDS
            #undef X
            #undef X_STR
            #undef X_COLOR
            break;
        }
        default: break;
    }
    return false;
}

ComponentMask diffAndEmitWal(const SystemState& old_s, const SystemState& new_s, WalRingBuffer& wal) {
    ComponentMask changed = 0;

    // ── SYSTEM_FIELDS ──────────────────────────────────────────
    {
        uint8_t tag = 0;
        #define X(type, name, def, bit, access) \
            if (old_s.system.name != new_s.system.name) { \
                if (bit != 0) changed |= (COMP::SYSTEM | bit); \
                else changed |= COMP::SYSTEM; \
                uint8_t buf[sizeof(type) > 160 ? sizeof(type) : 160]; \
                uint8_t len = serializeAny(new_s.system.name, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::SYSTEM), tag, buf, len); \
            } \
            tag++;

        #define X_STR(name, size, def, bit, access) \
            if (std::strncmp(old_s.system.name, new_s.system.name, size) != 0) { \
                if (bit != 0) changed |= (COMP::SYSTEM | bit); \
                else changed |= COMP::SYSTEM; \
                uint8_t buf[size]; \
                uint8_t len = serializeString(new_s.system.name, size, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::SYSTEM), tag, buf, len); \
            } \
            tag++;

        #define X_COLOR(name, def, bit, access) \
            if (old_s.system.name.r != new_s.system.name.r || \
                old_s.system.name.g != new_s.system.name.g || \
                old_s.system.name.b != new_s.system.name.b) { \
                if (bit != 0) changed |= (COMP::SYSTEM | bit); \
                else changed |= COMP::SYSTEM; \
                uint8_t buf[3]; \
                uint8_t len = serializeRgbColor(new_s.system.name, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::SYSTEM), tag, buf, len); \
            } \
            tag++;
        SYSTEM_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
    }

    // ── AUDIO_FIELDS ──────────────────────────────────────────
    {
        uint8_t tag = 0;
        #define X(type, name, def, bit, access) \
            if (old_s.audio.name != new_s.audio.name) { \
                if (bit != 0) changed |= (COMP::AUDIO | bit); \
                else changed |= COMP::AUDIO; \
                uint8_t buf[sizeof(type) > 160 ? sizeof(type) : 160]; \
                uint8_t len = serializeAny(new_s.audio.name, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::AUDIO), tag, buf, len); \
            } \
            tag++;

        #define X_STR(name, size, def, bit, access) \
            if (std::strncmp(old_s.audio.name, new_s.audio.name, size) != 0) { \
                if (bit != 0) changed |= (COMP::AUDIO | bit); \
                else changed |= COMP::AUDIO; \
                uint8_t buf[size]; \
                uint8_t len = serializeString(new_s.audio.name, size, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::AUDIO), tag, buf, len); \
            } \
            tag++;

        #define X_COLOR(name, def, bit, access) \
            if (old_s.audio.name.r != new_s.audio.name.r || \
                old_s.audio.name.g != new_s.audio.name.g || \
                old_s.audio.name.b != new_s.audio.name.b) { \
                if (bit != 0) changed |= (COMP::AUDIO | bit); \
                else changed |= COMP::AUDIO; \
                uint8_t buf[3]; \
                uint8_t len = serializeRgbColor(new_s.audio.name, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::AUDIO), tag, buf, len); \
            } \
            tag++;
        AUDIO_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
    }

    // ── PIPELINE_FIELDS ──────────────────────────────────────────
    {
        uint8_t tag = 0;
        #define X(type, name, def, bit, access) \
            if (old_s.pipeline.name != new_s.pipeline.name) { \
                if (bit != 0) changed |= (COMP::PIPELINE | bit); \
                else changed |= COMP::PIPELINE; \
                uint8_t buf[sizeof(type) > 160 ? sizeof(type) : 160]; \
                uint8_t len = serializeAny(new_s.pipeline.name, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::PIPELINE), tag, buf, len); \
            } \
            tag++;

        #define X_STR(name, size, def, bit, access) \
            if (std::strncmp(old_s.pipeline.name, new_s.pipeline.name, size) != 0) { \
                if (bit != 0) changed |= (COMP::PIPELINE | bit); \
                else changed |= COMP::PIPELINE; \
                uint8_t buf[size]; \
                uint8_t len = serializeString(new_s.pipeline.name, size, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::PIPELINE), tag, buf, len); \
            } \
            tag++;

        #define X_COLOR(name, def, bit, access) \
            if (old_s.pipeline.name.r != new_s.pipeline.name.r || \
                old_s.pipeline.name.g != new_s.pipeline.name.g || \
                old_s.pipeline.name.b != new_s.pipeline.name.b) { \
                if (bit != 0) changed |= (COMP::PIPELINE | bit); \
                else changed |= COMP::PIPELINE; \
                uint8_t buf[3]; \
                uint8_t len = serializeRgbColor(new_s.pipeline.name, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::PIPELINE), tag, buf, len); \
            } \
            tag++;
        PIPELINE_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
    }

    // ── ASSISTANT_FIELDS ──────────────────────────────────────────
    {
        uint8_t tag = 0;
        #define X(type, name, def, bit, access) \
            if (old_s.assistant.name != new_s.assistant.name) { \
                if (bit != 0) changed |= (COMP::ASSISTANT | bit); \
                else changed |= COMP::ASSISTANT; \
                uint8_t buf[sizeof(type) > 160 ? sizeof(type) : 160]; \
                uint8_t len = serializeAny(new_s.assistant.name, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::ASSISTANT), tag, buf, len); \
            } \
            tag++;

        #define X_STR(name, size, def, bit, access) \
            if (std::strncmp(old_s.assistant.name, new_s.assistant.name, size) != 0) { \
                if (bit != 0) changed |= (COMP::ASSISTANT | bit); \
                else changed |= COMP::ASSISTANT; \
                uint8_t buf[size]; \
                uint8_t len = serializeString(new_s.assistant.name, size, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::ASSISTANT), tag, buf, len); \
            } \
            tag++;

        #define X_COLOR(name, def, bit, access) \
            if (old_s.assistant.name.r != new_s.assistant.name.r || \
                old_s.assistant.name.g != new_s.assistant.name.g || \
                old_s.assistant.name.b != new_s.assistant.name.b) { \
                if (bit != 0) changed |= (COMP::ASSISTANT | bit); \
                else changed |= COMP::ASSISTANT; \
                uint8_t buf[3]; \
                uint8_t len = serializeRgbColor(new_s.assistant.name, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::ASSISTANT), tag, buf, len); \
            } \
            tag++;
        ASSISTANT_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
    }

    // ── LED_FIELDS ──────────────────────────────────────────
    {
        uint8_t tag = 0;
        #define X(type, name, def, bit, access) \
            if (old_s.led.name != new_s.led.name) { \
                if (bit != 0) changed |= (COMP::LED | bit); \
                else changed |= COMP::LED; \
                uint8_t buf[sizeof(type) > 160 ? sizeof(type) : 160]; \
                uint8_t len = serializeAny(new_s.led.name, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::LED), tag, buf, len); \
            } \
            tag++;

        #define X_STR(name, size, def, bit, access) \
            if (std::strncmp(old_s.led.name, new_s.led.name, size) != 0) { \
                if (bit != 0) changed |= (COMP::LED | bit); \
                else changed |= COMP::LED; \
                uint8_t buf[size]; \
                uint8_t len = serializeString(new_s.led.name, size, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::LED), tag, buf, len); \
            } \
            tag++;

        #define X_COLOR(name, def, bit, access) \
            if (old_s.led.name.r != new_s.led.name.r || \
                old_s.led.name.g != new_s.led.name.g || \
                old_s.led.name.b != new_s.led.name.b) { \
                if (bit != 0) changed |= (COMP::LED | bit); \
                else changed |= COMP::LED; \
                uint8_t buf[3]; \
                uint8_t len = serializeRgbColor(new_s.led.name, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::LED), tag, buf, len); \
            } \
            tag++;
        LED_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
    }

    // ── MQTT_FIELDS ──────────────────────────────────────────
    {
        uint8_t tag = 0;
        #define X(type, name, def, bit, access) \
            if (old_s.mqtt.name != new_s.mqtt.name) { \
                if (bit != 0) changed |= (COMP::MQTT | bit); \
                else changed |= COMP::MQTT; \
                uint8_t buf[sizeof(type) > 160 ? sizeof(type) : 160]; \
                uint8_t len = serializeAny(new_s.mqtt.name, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::MQTT), tag, buf, len); \
            } \
            tag++;

        #define X_STR(name, size, def, bit, access) \
            if (std::strncmp(old_s.mqtt.name, new_s.mqtt.name, size) != 0) { \
                if (bit != 0) changed |= (COMP::MQTT | bit); \
                else changed |= COMP::MQTT; \
                uint8_t buf[size]; \
                uint8_t len = serializeString(new_s.mqtt.name, size, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::MQTT), tag, buf, len); \
            } \
            tag++;

        #define X_COLOR(name, def, bit, access) \
            if (old_s.mqtt.name.r != new_s.mqtt.name.r || \
                old_s.mqtt.name.g != new_s.mqtt.name.g || \
                old_s.mqtt.name.b != new_s.mqtt.name.b) { \
                if (bit != 0) changed |= (COMP::MQTT | bit); \
                else changed |= COMP::MQTT; \
                uint8_t buf[3]; \
                uint8_t len = serializeRgbColor(new_s.mqtt.name, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::MQTT), tag, buf, len); \
            } \
            tag++;
        MQTT_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
    }

    // ── ALARM_FIELDS ──────────────────────────────────────────
    {
        uint8_t tag = 0;
        #define X(type, name, def, bit, access) \
            if (old_s.alarm.name != new_s.alarm.name) { \
                if (bit != 0) changed |= (COMP::ALARM | bit); \
                else changed |= COMP::ALARM; \
                uint8_t buf[sizeof(type) > 160 ? sizeof(type) : 160]; \
                uint8_t len = serializeAny(new_s.alarm.name, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::ALARM), tag, buf, len); \
            } \
            tag++;

        #define X_STR(name, size, def, bit, access) \
            if (std::strncmp(old_s.alarm.name, new_s.alarm.name, size) != 0) { \
                if (bit != 0) changed |= (COMP::ALARM | bit); \
                else changed |= COMP::ALARM; \
                uint8_t buf[size]; \
                uint8_t len = serializeString(new_s.alarm.name, size, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::ALARM), tag, buf, len); \
            } \
            tag++;

        #define X_COLOR(name, def, bit, access) \
            if (old_s.alarm.name.r != new_s.alarm.name.r || \
                old_s.alarm.name.g != new_s.alarm.name.g || \
                old_s.alarm.name.b != new_s.alarm.name.b) { \
                if (bit != 0) changed |= (COMP::ALARM | bit); \
                else changed |= COMP::ALARM; \
                uint8_t buf[3]; \
                uint8_t len = serializeRgbColor(new_s.alarm.name, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::ALARM), tag, buf, len); \
            } \
            tag++;
        ALARM_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
    }

    // ── BLUETOOTH_FIELDS ──────────────────────────────────────────
    {
        uint8_t tag = 0;
        #define X(type, name, def, bit, access) \
            if (old_s.bluetooth.name != new_s.bluetooth.name) { \
                if (bit != 0) changed |= (COMP::BLUETOOTH | bit); \
                else changed |= COMP::BLUETOOTH; \
                uint8_t buf[sizeof(type) > 160 ? sizeof(type) : 160]; \
                uint8_t len = serializeAny(new_s.bluetooth.name, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::BLUETOOTH), tag, buf, len); \
            } \
            tag++;

        #define X_STR(name, size, def, bit, access) \
            if (std::strncmp(old_s.bluetooth.name, new_s.bluetooth.name, size) != 0) { \
                if (bit != 0) changed |= (COMP::BLUETOOTH | bit); \
                else changed |= COMP::BLUETOOTH; \
                uint8_t buf[size]; \
                uint8_t len = serializeString(new_s.bluetooth.name, size, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::BLUETOOTH), tag, buf, len); \
            } \
            tag++;

        #define X_COLOR(name, def, bit, access) \
            if (old_s.bluetooth.name.r != new_s.bluetooth.name.r || \
                old_s.bluetooth.name.g != new_s.bluetooth.name.g || \
                old_s.bluetooth.name.b != new_s.bluetooth.name.b) { \
                if (bit != 0) changed |= (COMP::BLUETOOTH | bit); \
                else changed |= COMP::BLUETOOTH; \
                uint8_t buf[3]; \
                uint8_t len = serializeRgbColor(new_s.bluetooth.name, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::BLUETOOTH), tag, buf, len); \
            } \
            tag++;
        BLUETOOTH_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
    }

    // ── MEDIA_FIELDS ──────────────────────────────────────────
    {
        uint8_t tag = 0;
        #define X(type, name, def, bit, access) \
            if (old_s.media.name != new_s.media.name) { \
                if (bit != 0) changed |= (COMP::MEDIA | bit); \
                else changed |= COMP::MEDIA; \
                uint8_t buf[sizeof(type) > 160 ? sizeof(type) : 160]; \
                uint8_t len = serializeAny(new_s.media.name, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::MEDIA), tag, buf, len); \
            } \
            tag++;

        #define X_STR(name, size, def, bit, access) \
            if (std::strncmp(old_s.media.name, new_s.media.name, size) != 0) { \
                if (bit != 0) changed |= (COMP::MEDIA | bit); \
                else changed |= COMP::MEDIA; \
                uint8_t buf[size]; \
                uint8_t len = serializeString(new_s.media.name, size, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::MEDIA), tag, buf, len); \
            } \
            tag++;

        #define X_COLOR(name, def, bit, access) \
            if (old_s.media.name.r != new_s.media.name.r || \
                old_s.media.name.g != new_s.media.name.g || \
                old_s.media.name.b != new_s.media.name.b) { \
                if (bit != 0) changed |= (COMP::MEDIA | bit); \
                else changed |= COMP::MEDIA; \
                uint8_t buf[3]; \
                uint8_t len = serializeRgbColor(new_s.media.name, buf, sizeof(buf)); \
                wal.push(static_cast<uint8_t>(ComponentId::MEDIA), tag, buf, len); \
            } \
            tag++;
        MEDIA_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
    }

    return changed;
}

void serializeSnapshot(const SystemState& state, uint32_t head_seq, std::vector<WalRecordEntry>& out_snapshot) {
    out_snapshot.clear();

    auto add_entry = [&](ComponentId comp, uint8_t tag, const uint8_t* val, uint8_t len) {
        WalRecordEntry e;
        e.seq = head_seq;
        e.component_id = static_cast<uint8_t>(comp);
        e.field_tag = tag;
        e.value.assign(val, val + len);
        out_snapshot.push_back(std::move(e));
    };

    // ── Snapshot Component: SYSTEM ─────────────────────────────
    {
        uint8_t tag = 0;
        #define X(type, name, def, bit, access) { \
            uint8_t buf[sizeof(type) > 160 ? sizeof(type) : 160]; \
            uint8_t len = serializeAny(state.system.name, buf, sizeof(buf)); \
            add_entry(ComponentId::SYSTEM, tag++, buf, len); \
        }

        #define X_STR(name, size, def, bit, access) { \
            uint8_t buf[size]; \
            uint8_t len = serializeString(state.system.name, size, buf, sizeof(buf)); \
            add_entry(ComponentId::SYSTEM, tag++, buf, len); \
        }

        #define X_COLOR(name, def, bit, access) { \
            uint8_t buf[3]; \
            uint8_t len = serializeRgbColor(state.system.name, buf, sizeof(buf)); \
            add_entry(ComponentId::SYSTEM, tag++, buf, len); \
        }
        SYSTEM_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
    }

    // ── Snapshot Component: AUDIO ─────────────────────────────
    {
        uint8_t tag = 0;
        #define X(type, name, def, bit, access) { \
            uint8_t buf[sizeof(type) > 160 ? sizeof(type) : 160]; \
            uint8_t len = serializeAny(state.audio.name, buf, sizeof(buf)); \
            add_entry(ComponentId::AUDIO, tag++, buf, len); \
        }

        #define X_STR(name, size, def, bit, access) { \
            uint8_t buf[size]; \
            uint8_t len = serializeString(state.audio.name, size, buf, sizeof(buf)); \
            add_entry(ComponentId::AUDIO, tag++, buf, len); \
        }

        #define X_COLOR(name, def, bit, access) { \
            uint8_t buf[3]; \
            uint8_t len = serializeRgbColor(state.audio.name, buf, sizeof(buf)); \
            add_entry(ComponentId::AUDIO, tag++, buf, len); \
        }
        AUDIO_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
    }

    // ── Snapshot Component: PIPELINE ─────────────────────────────
    {
        uint8_t tag = 0;
        #define X(type, name, def, bit, access) { \
            uint8_t buf[sizeof(type) > 160 ? sizeof(type) : 160]; \
            uint8_t len = serializeAny(state.pipeline.name, buf, sizeof(buf)); \
            add_entry(ComponentId::PIPELINE, tag++, buf, len); \
        }

        #define X_STR(name, size, def, bit, access) { \
            uint8_t buf[size]; \
            uint8_t len = serializeString(state.pipeline.name, size, buf, sizeof(buf)); \
            add_entry(ComponentId::PIPELINE, tag++, buf, len); \
        }

        #define X_COLOR(name, def, bit, access) { \
            uint8_t buf[3]; \
            uint8_t len = serializeRgbColor(state.pipeline.name, buf, sizeof(buf)); \
            add_entry(ComponentId::PIPELINE, tag++, buf, len); \
        }
        PIPELINE_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
    }

    // ── Snapshot Component: ASSISTANT ─────────────────────────────
    {
        uint8_t tag = 0;
        #define X(type, name, def, bit, access) { \
            uint8_t buf[sizeof(type) > 160 ? sizeof(type) : 160]; \
            uint8_t len = serializeAny(state.assistant.name, buf, sizeof(buf)); \
            add_entry(ComponentId::ASSISTANT, tag++, buf, len); \
        }

        #define X_STR(name, size, def, bit, access) { \
            uint8_t buf[size]; \
            uint8_t len = serializeString(state.assistant.name, size, buf, sizeof(buf)); \
            add_entry(ComponentId::ASSISTANT, tag++, buf, len); \
        }

        #define X_COLOR(name, def, bit, access) { \
            uint8_t buf[3]; \
            uint8_t len = serializeRgbColor(state.assistant.name, buf, sizeof(buf)); \
            add_entry(ComponentId::ASSISTANT, tag++, buf, len); \
        }
        ASSISTANT_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
    }

    // ── Snapshot Component: LED ─────────────────────────────
    {
        uint8_t tag = 0;
        #define X(type, name, def, bit, access) { \
            uint8_t buf[sizeof(type) > 160 ? sizeof(type) : 160]; \
            uint8_t len = serializeAny(state.led.name, buf, sizeof(buf)); \
            add_entry(ComponentId::LED, tag++, buf, len); \
        }

        #define X_STR(name, size, def, bit, access) { \
            uint8_t buf[size]; \
            uint8_t len = serializeString(state.led.name, size, buf, sizeof(buf)); \
            add_entry(ComponentId::LED, tag++, buf, len); \
        }

        #define X_COLOR(name, def, bit, access) { \
            uint8_t buf[3]; \
            uint8_t len = serializeRgbColor(state.led.name, buf, sizeof(buf)); \
            add_entry(ComponentId::LED, tag++, buf, len); \
        }
        LED_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
    }

    // ── Snapshot Component: MQTT ─────────────────────────────
    {
        uint8_t tag = 0;
        #define X(type, name, def, bit, access) { \
            uint8_t buf[sizeof(type) > 160 ? sizeof(type) : 160]; \
            uint8_t len = serializeAny(state.mqtt.name, buf, sizeof(buf)); \
            add_entry(ComponentId::MQTT, tag++, buf, len); \
        }

        #define X_STR(name, size, def, bit, access) { \
            uint8_t buf[size]; \
            uint8_t len = serializeString(state.mqtt.name, size, buf, sizeof(buf)); \
            add_entry(ComponentId::MQTT, tag++, buf, len); \
        }

        #define X_COLOR(name, def, bit, access) { \
            uint8_t buf[3]; \
            uint8_t len = serializeRgbColor(state.mqtt.name, buf, sizeof(buf)); \
            add_entry(ComponentId::MQTT, tag++, buf, len); \
        }
        MQTT_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
    }

    // ── Snapshot Component: ALARM ─────────────────────────────
    {
        uint8_t tag = 0;
        #define X(type, name, def, bit, access) { \
            uint8_t buf[sizeof(type) > 160 ? sizeof(type) : 160]; \
            uint8_t len = serializeAny(state.alarm.name, buf, sizeof(buf)); \
            add_entry(ComponentId::ALARM, tag++, buf, len); \
        }

        #define X_STR(name, size, def, bit, access) { \
            uint8_t buf[size]; \
            uint8_t len = serializeString(state.alarm.name, size, buf, sizeof(buf)); \
            add_entry(ComponentId::ALARM, tag++, buf, len); \
        }

        #define X_COLOR(name, def, bit, access) { \
            uint8_t buf[3]; \
            uint8_t len = serializeRgbColor(state.alarm.name, buf, sizeof(buf)); \
            add_entry(ComponentId::ALARM, tag++, buf, len); \
        }
        ALARM_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
    }

    // ── Snapshot Component: BLUETOOTH ─────────────────────────────
    {
        uint8_t tag = 0;
        #define X(type, name, def, bit, access) { \
            uint8_t buf[sizeof(type) > 160 ? sizeof(type) : 160]; \
            uint8_t len = serializeAny(state.bluetooth.name, buf, sizeof(buf)); \
            add_entry(ComponentId::BLUETOOTH, tag++, buf, len); \
        }

        #define X_STR(name, size, def, bit, access) { \
            uint8_t buf[size]; \
            uint8_t len = serializeString(state.bluetooth.name, size, buf, sizeof(buf)); \
            add_entry(ComponentId::BLUETOOTH, tag++, buf, len); \
        }

        #define X_COLOR(name, def, bit, access) { \
            uint8_t buf[3]; \
            uint8_t len = serializeRgbColor(state.bluetooth.name, buf, sizeof(buf)); \
            add_entry(ComponentId::BLUETOOTH, tag++, buf, len); \
        }
        BLUETOOTH_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
    }

    // ── Snapshot Component: MEDIA ─────────────────────────────
    {
        uint8_t tag = 0;
        #define X(type, name, def, bit, access) { \
            uint8_t buf[sizeof(type) > 160 ? sizeof(type) : 160]; \
            uint8_t len = serializeAny(state.media.name, buf, sizeof(buf)); \
            add_entry(ComponentId::MEDIA, tag++, buf, len); \
        }

        #define X_STR(name, size, def, bit, access) { \
            uint8_t buf[size]; \
            uint8_t len = serializeString(state.media.name, size, buf, sizeof(buf)); \
            add_entry(ComponentId::MEDIA, tag++, buf, len); \
        }

        #define X_COLOR(name, def, bit, access) { \
            uint8_t buf[3]; \
            uint8_t len = serializeRgbColor(state.media.name, buf, sizeof(buf)); \
            add_entry(ComponentId::MEDIA, tag++, buf, len); \
        }
        MEDIA_FIELDS
        #undef X
        #undef X_STR
        #undef X_COLOR
    }

}

} // namespace SysDbCodec
